# config/services.yaml

parameters:
    cloudinary_url: '%env(CLOUDINARY_URL)%'
    profile_picture_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Cloudinary service
    Cloudinary\Cloudinary:
        arguments:
            - '%cloudinary_url%'

    # Twilio Client service
    Twilio\Rest\Client:
        arguments:
            - '%twilio_sid%'
            - '%twilio_auth_token%'

    # Explicit controller configurations
    App\Controller\Admin\ReclammationCrudController:
        arguments:
            $twilio: '@Twilio\Rest\Client'

    App\Controller\ReponseReclamationController:
        arguments:
            $twilio: '@Twilio\Rest\Client'

    App\Controller\ProfileController:
        arguments:
            $cloudinary: '@Cloudinary\Cloudinary'