# config/services.yaml

parameters:
    cloudinary_url: '%env(CLOUDINARY_URL)%'
    profile_picture_directory: '%kernel.project_dir%/public/uploads/profile_pictures'

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service Cloudinary
    cloudinary:
        class: Cloudinary\Cloudinary
        arguments:
            - '%cloudinary_url%'

    # Alias pour lier Cloudinary\Cloudinary au service 'cloudinary'
    Cloudinary\Cloudinary: '@cloudinary'

    # Twilio Client
    twilio.client:
        class: Twilio\Rest\Client
        arguments:
            - '%env(TWILIO_SID)%'
            - '%env(TWILIO_AUTH_TOKEN)%'

    # ReclammationCrudController with Twilio
    App\Controller\Admin\ReclammationCrudController:
        arguments:
            $twilio: '@twilio.client'

    # ReponseReclamationController with Twilio
    App\Controller\ReponseReclamationController:
        arguments:
            $twilio: '@twilio.client'