# config/services.yaml

parameters:
    cloudinary_url: '%env(CLOUDINARY_URL)%'
    profile_picture_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Cloudinary service
    Cloudinary\Cloudinary:
        arguments:
            - '%cloudinary_url%'

    # Twilio Client
    twilio.client:
        class: Twilio\Rest\Client
        arguments:
            - '%env(TWILIO_SID)%'
            - '%env(TWILIO_AUTH_TOKEN)%'

    # ReclammationCrudController with Twilio
    App\Controller\Admin\ReclammationCrudController:
        arguments:
            $twilio: '@twilio.client'

    # ReponseReclamationController with Twilio
    App\Controller\ReponseReclamationController:
        arguments:
            $twilio: '@twilio.client'

    App\Controller\ProfileController:
        arguments:
            $cloudinary: '@Cloudinary\Cloudinary'
    # TextRazor        
    App\Service\TextRazorService:
        arguments:
            $apiKey: '%env(TEXTRAZOR_API_KEY)%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'